// ListadeComunas.js
const comunas = [
    'Arica', 'Camarones', 'General Lagos', 'Putre', 'Alto Hospicio', 'Iquique', 'Camiña', 'Colchane', 'Huara', 'Pica', 
    'Pozo Almonte', 'Tocopilla', 'María Elena', 'Calama', 'Ollague', 'San Pedro de Atacama', 'Antofagasta', 'Mejillones', 
    'Sierra Gorda', 'Taltal', 'Chañaral', 'Diego de Almagro', 'Copiapó', 'Caldera', 'Tierra Amarilla', 'Vallenar', 
    'Alto del Carmen', 'Freirina', 'Huasco', 'La Serena', 'Coquimbo', 'Andacollo', 'La Higuera', 'Paihuano', 'Vicuña', 
    'Ovalle', 'Combarbalá', 'Monte Patria', 'Punitaqui', 'Río Hurtado', 'Illapel', 'Canela', 'Los Vilos', 'Salamanca', 
    'La Ligua', 'Cabildo', 'Zapallar', 'Papudo', 'Petorca', 'Los Andes', 'San Esteban', 'Calle Larga', 'Rinconada', 
    'San Felipe', 'Llaillay', 'Putaendo', 'Santa María', 'Catemu', 'Panquehue', 'Quillota', 'La Cruz', 'La Calera', 
    'Nogales', 'Hijuelas', 'Valparaíso', 'Viña del Mar', 'Concón', 'Quintero', 'Puchuncaví', 'Casablanca', 
    'Juan Fernández', 'San Antonio', 'Cartagena', 'El Tabo', 'El Quisco', 'Algarrobo', 'Santo Domingo', 'Isla de Pascua', 
    'Quilpué', 'Limache', 'Olmué', 'Villa Alemana', 'Colina', 'Lampa', 'Tiltil', 'Santiago', 'Vitacura', 'San Ramón', 
    'San Miguel', 'San Joaquín', 'Renca', 'Recoleta', 'Quinta Normal', 'Quilicura', 'Pudahuel', 'Providencia', 'Peñalolén', 
    'Pedro Aguirre Cerda', 'Ñuñoa', 'Maipú', 'Macul', 'Lo Prado', 'Lo Espejo', 'Lo Barnechea', 'Las Condes', 'La Reina', 
    'La Pintana', 'La Granja', 'La Florida', 'La Cisterna', 'Independencia', 'Huechuraba', 'Estación Central', 'El Bosque', 
    'Conchalí', 'Cerro Navia', 'Cerrillos', 'Puente Alto', 'San José de Maipo', 'Pirque', 'San Bernardo', 'Buin', 'Paine', 
    'Calera de Tango', 'Melipilla', 'Alhué', 'Curacaví', 'María Pinto', 'San Pedro', 'Isla de Maipo', 'El Monte', 'Padre Hurtado', 
    'Peñaflor', 'Talagante', 'Codegua', 'Coínco', 'Coltauco', 'Doñihue', 'Graneros', 'Las Cabras', 'Machalí', 'Malloa', 'Mostazal', 
    'Olivar', 'Peumo', 'Pichidegua', 'Quinta de Tilcoco', 'Rancagua', 'Rengo', 'Requínoa', 'San Vicente de Tagua Tagua', 'Chépica', 
    'Chimbarongo', 'Lolol', 'Nancagua', 'Palmilla', 'Peralillo', 'Placilla', 'Pumanque', 'San Fernando', 'Santa Cruz', 'La Estrella', 
    'Litueche', 'Marchigüe', 'Navidad', 'Paredones', 'Pichilemu', 'Curicó', 'Hualañé', 'Licantén', 'Molina', 'Rauco', 'Romeral', 
    'Sagrada Familia', 'Teno', 'Vichuquén', 'Talca', 'San Clemente', 'Pelarco', 'Pencahue', 'Maule', 'San Rafael', 'Curepto', 
    'Constitución', 'Empedrado', 'Río Claro', 'Linares', 'San Javier', 'Parral', 'Villa Alegre', 'Longaví', 'Colbún', 'Retiro', 
    'Yerbas Buenas', 'Cauquenes', 'Chanco', 'Pelluhue', 'Bulnes', 'Chillán', 'Chillán Viejo', 'El Carmen', 'Pemuco', 'Pinto', 
    'Quillón', 'San Ignacio', 'Yungay', 'Cobquecura', 'Coelemu', 'Ninhue', 'Portezuelo', 'Quirihue', 'Ránquil', 'Treguaco', 
    'San Carlos', 'Coihueco', 'San Nicolás', 'Ñiquén', 'San Fabián', 'Alto Biobío', 'Antuco', 'Cabrero', 'Laja', 'Los Ángeles', 
    'Mulchén', 'Nacimiento', 'Negrete', 'Quilaco', 'Quilleco', 'San Rosendo', 'Santa Bárbara', 'Tucapel', 'Yumbel', 'Concepción', 
    'Coronel', 'Chiguayante', 'Florida', 'Hualpén', 'Hualqui', 'Lota', 'Penco', 'San Pedro de La Paz', 'Santa Juana', 'Talcahuano', 
    'Tomé', 'Arauco', 'Cañete', 'Contulmo', 'Curanilahue', 'Lebu', 'Los Álamos', 'Tirúa', 'Angol', 'Collipulli', 'Curacautín', 'Ercilla', 
    'Lonquimay', 'Los Sauces', 'Lumaco', 'Purén', 'Renaico', 'Traiguén', 'Victoria', 'Temuco', 'Carahue', 'Cholchol', 'Cunco', 'Curarrehue', 
    'Freire', 'Galvarino', 'Gorbea', 'Lautaro', 'Loncoche', 'Melipeuco', 'Nueva Imperial', 'Padre Las Casas', 'Perquenco', 'Pitrufquén', 
    'Pucón', 'Saavedra', 'Teodoro Schmidt', 'Toltén', 'Vilcún', 'Villarrica', 'Valdivia', 'Corral', 'Lanco', 'Los Lagos', 'Máfil', 'Mariquina', 
    'Paillaco', 'Panguipulli', 'La Unión', 'Futrono', 'Lago Ranco', 'Río Bueno', 'Osorno', 'Puerto Octay', 'Purranque', 'Puyehue', 'Río Negro', 
    'San Juan de la Costa', 'San Pablo', 'Calbuco', 'Cochamó', 'Fresia', 'Frutillar', 'Llanquihue', 'Los Muermos', 'Maullín', 'Puerto Montt', 
    'Puerto Varas', 'Ancud', 'Castro', 'Chonchi', 'Curaco de Vélez', 'Dalcahue', 'Puqueldón', 'Queilén', 'Quellón', 'Quemchi', 'Quinchao', 
    'Chaitén', 'Futaleufú', 'Hualaihué', 'Palena', 'Lago Verde', 'Coihaique', 'Aysén', 'Cisnes', 'Guaitecas', 'Río Ibáñez', 'Chile Chico', 
    'Cochrane','Higgins', 'Tortel', 'Natales', 'Torres del Paine', 'Laguna Blanca', 'Punta Arenas', 'Río Verde', 'San Gregorio', 'Porvenir', 
    'Primavera', 'Timaukel', 'Cabo de Hornos', 'Antártica'
];  
export default comunas;
  